"""Add provider verification fields to skills

Revision ID: 7fc82049fb21
Revises: aafa0ed79a99
Create Date: 2026-05-06 15:00:27.954943
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fc82049fb21'
down_revision: Union[str, None] = 'aafa0ed79a99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('verification_status', sa.String(length=20), nullable=False, server_default='unverified'))
    op.add_column('skills', sa.Column('verified_node_pubkey', sa.String(length=66), nullable=True))
    op.add_column('skills', sa.Column('verified_domain', sa.String(length=255), nullable=True))
    op.add_column('skills', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('skills', sa.Column('verification_challenge', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'verification_challenge')
    op.drop_column('skills', 'verified_at')
    op.drop_column('skills', 'verified_domain')
    op.drop_column('skills', 'verified_node_pubkey')
    op.drop_column('skills', 'verification_status')
    # ### end Alembic commands ###
