"""Add unique constraint on rating execution_id

Revision ID: aafa0ed79a99
Revises: bab4c7e4bcae
Create Date: 2026-05-06 10:35:42.838306
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aafa0ed79a99'
down_revision: Union[str, None] = 'bab4c7e4bcae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
