"""Add unique constraint on rating execution_id

Revision ID: bab4c7e4bcae
Revises: ed0aef0bc1ea
Create Date: 2026-05-06 10:35:04.455226
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab4c7e4bcae'
down_revision: Union[str, None] = 'ed0aef0bc1ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
