"""Add unique constraint on rating execution_id

Revision ID: ed0aef0bc1ea
Revises: e5ca7b709dad
Create Date: 2026-05-06 10:33:28.177116
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0aef0bc1ea'
down_revision: Union[str, None] = 'e5ca7b709dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('one_rating_per_execution', 'ratings', ['execution_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('one_rating_per_execution', 'ratings', type_='unique')
    # ### end Alembic commands ###
